title: "honey"
description: родительская школа
author: "Кирилл Назаров"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-readme-index
- jekyll-github-metadata

# Для GitHub Pages (проектный сайт)
baseurl: "/honey"
url: "https://nazarovki.github.io"

# Настройки по умолчанию
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      # Это ключ! Посты будут по адресу /2026/07/05/go/
      permalink: "/:year/:month/:day/:title/"

collections:
  notes:
    output: true
    permalink: /notes/:path/

# _config.yml
mermaid:
  initialize: # сюда можно передать JSON-объект с настройками Mermaid
    theme: 'dark'
